# NOTE: update this with your service name
service: spikelabs-delivery-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: sa-east-1
  environment:
    tableName: orders
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  create:
    handler: create.main
    events:
      - http:
          path: orders
          method: post
          authorizer: aws_iam
          cors: true

  get:
    handler: get.main
    events:
      - http:
          path: orders/{id}
          method: get
          authorizer: aws_iam
          cors: true

  list:
    handler: list.main
    events:
      - http:
          path: orders
          method: get
          authorizer: aws_iam
          cors: true

resources:
  - ${file(resources/api-gateway-errors.yml)}

